apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: php-lev
spec:
  maxReplicas: 20
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: php-lev
  targetCPUUtilizationPercentage: 50
